name: Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile
    - run: npm pack
    - name: Save package artifact
      uses: actions/upload-artifact@v2
      with:
        name: bindle-js
        path: bindle-js-*.tgz
